# Generated by Django 5.0.2 on 2024-03-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todoform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoform',
            name='user',
        ),
    ]
